---
name: Update dependent repositories
on:
  push:
    branches:
      - master
#  workflow_run:
#    types:
#      - completed
#    workflows:
#      - 'automerge'
jobs:
  update-dependent-repositories:
    strategy:
      matrix:
        repository: [test-actions-4]
    name: Update ${{ matrix.repository }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'Mixaster995' || github.event_name == 'push' }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          repository: ${{ github.repository }}
          token: ${{ secrets.TEST_SECRET }}
      - name: Find merged PR
        uses: jwalton/gh-find-current-pr@v1.0.2
        id: findPr
        with:
          github-token: ${{ github.token }}
      - name: Create commit message
        working-directory: ${{ github.repository }}
        run: |
          echo "Update go.mod and go.sum to latest version from ${{ github.repository }}@main" >> /tmp/commit-message
          echo "PR link: https://github.com/${{ github.repository }}/pull/${{ steps.findPr.outputs.number }}" >> /tmp/commit-message
          echo "" >> /tmp/commit-message
          LOG_MSG=$(git log --date=iso --pretty='format:Commit: %h%nAuthor: %an%nDate: %ad%nMessage:%n  - %B%n' -1 | sed '/^$/d;$d')
          for((i=2;i<=18;i+=2)); do n=$(printf '%*s' $((i+2))) m=$(printf '%*s' $i) LOG_MSG=$(echo "$LOG_MSG" | tr '\n' '|' | sed "s/${m}-/${n}-/2g" | tr '|' '\n'); done
          echo "$LOG_MSG" >> /tmp/commit-message
          echo "Commit Message: "
          cat /tmp/commit-message

      - name: Checkout Mixaster995/${{ matrix.repository }}
        uses: actions/checkout@v2
        with:
          path: Mixaster995/${{ matrix.repository }}
          repository: Mixaster995/${{ matrix.repository }}
          token: ${{ secrets.TEST_SECRET }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Update ${{ github.repository }} locally
        working-directory: Mixaster995/${{ matrix.repository }}
        run: |
          GOPRIVATE=github.com/Mixaster995 go get -u github.com/${{ github.repository }}@master
          go mod tidy
          git diff
      - name: Push update to the ${{ matrix.repository }}
        working-directory: Mixaster995/${{ matrix.repository }}
        run: |
          echo Starting to update repository ${{ matrix.repository }}
          git config --global user.email "avramenkomihail15@gmail.com"
          git config --global user.name "Mikhail Avramenko"
          git add go.mod go.sum
          git commit -s -F /tmp/commit-message
          git checkout -b update/${{ github.repository }}
          git push -f origin update/${{ github.repository }}
